Repository kubernetes-sigs/secrets-store-sync-controller, pull requests merged in 2024-07, with the labels that each got.

#45 test: adds secret util tests
  go.mod
  pkg/util/secretutil/secret.go
  pkg/util/secretutil/secret_test.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/XL

#36 test: adds unit tests for Reconcile
  internal/controller/conditions.go
  internal/controller/secretsync_controller.go
  internal/controller/secretsync_controller_test.go
Labels: kind/feature, approved, tide/merge-method-squash, cncf-cla: yes, lgtm, size/L

#40 test: add e2e provider tests
  Makefile
  manifest_staging/charts/secrets-store-sync-controller/values.yaml
  test/bats/README.md
  test/bats/e2e-provider.bats
  test/bats/helpers.bash
Labels: kind/feature, approved, ok-to-test, cncf-cla: yes, lgtm, size/L
