Repository kubernetes-sigs/secrets-store-sync-controller, pull requests merged in 2024-08, with the labels that each got.

#48 feat: adds multi arch image build
  Makefile
  config/manager/manager.yaml
  docker/Makefile
  docker/build.sh
  docker/cloudbuild.yaml
  manifest_staging/charts/secrets-store-sync-controller/values.yaml
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/L

#50 test: add e2e vap tests
  config/validatingadmissionpolicies/update_owners_check_old_object.yaml
  manifest_staging/charts/secrets-store-sync-controller/templates/update_owners_check_old_object.yaml
  test/bats/README.md
  test/bats/e2e-provider.bats
  test/bats/helpers.bash
  test/bats/tests/e2e_provider/api_credential_secretsync.yaml
  test/bats/tests/e2e_provider/invalid_annotation_key_secretsync.yaml
  test/bats/tests/e2e_provider/invalid_annotation_value_secretsync.yaml
  test/bats/tests/e2e_provider/invalid_label_key_secretsync.yaml
  test/bats/tests/e2e_provider/invalid_label_value_secretsync.yaml
  test/bats/tests/e2e_provider/service_account_token_secretsync.yaml
Labels: kind/feature, approved, ok-to-test, cncf-cla: yes, lgtm, size/L

#55 chore: release prep
  .github/workflows/e2e-provider-tests.yaml
  Makefile
Labels: kind/feature, size/M, approved, cncf-cla: yes, lgtm

#63 fix: fixes helm chart publish
  .github/workflows/create-release.yaml
  .github/workflows/e2e-provider-tests.yaml
  .github/workflows/publish-helm-chart.yaml
  .github/workflows/scorecards.yaml
  .goreleaser.yml
  Makefile
  charts/secrets-store-sync-controller/.helmignore
  charts/secrets-store-sync-controller/Chart.yaml
  charts/secrets-store-sync-controller/README.md
  charts/secrets-store-sync-controller/crds/secret-sync.x-k8s.io_secretsyncs.yaml
  charts/secrets-store-sync-controller/crds/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  charts/secrets-store-sync-controller/templates/VAPB_create_update_secrets_type.yaml
  charts/secrets-store-sync-controller/templates/VAPB_create_update_token_request_deny.yaml
  charts/secrets-store-sync-controller/templates/VAPB_delete_secrets.yaml
  charts/secrets-store-sync-controller/templates/VAPB_update_owners_check_old_object.yaml
  charts/secrets-store-sync-controller/templates/VAPB_update_secrets_based_on_label.yaml
  charts/secrets-store-sync-controller/templates/VAPB_validate_annotation_format_secret_sync.yaml
  charts/secrets-store-sync-controller/templates/VAPB_validate_label_format_secret_sync.yaml
  charts/secrets-store-sync-controller/templates/VAPB_validate_token_config.yaml
  charts/secrets-store-sync-controller/templates/_helpers.tpl
  charts/secrets-store-sync-controller/templates/create_update_secrets_types.yaml
  charts/secrets-store-sync-controller/templates/create_update_token_request_deny.yaml
  charts/secrets-store-sync-controller/templates/delete_secrets.yaml
  charts/secrets-store-sync-controller/templates/leader_election_role.yaml
  charts/secrets-store-sync-controller/templates/leader_election_role_binding.yaml
  charts/secrets-store-sync-controller/templates/secrets-store-sync-controller.yaml
  charts/secrets-store-sync-controller/templates/secretsync_editor_role.yaml
  charts/secrets-store-sync-controller/templates/secretsync_viewer_role.yaml
  charts/secrets-store-sync-controller/templates/update_owners_check_old_object.yaml
  charts/secrets-store-sync-controller/templates/update_secrets_based_on_label.yaml
  charts/secrets-store-sync-controller/templates/validate_annotation_format_secret_sync.yaml
  charts/secrets-store-sync-controller/templates/validate_label_format_secret_sync.yaml
  charts/secrets-store-sync-controller/templates/validate_token_config.yaml
  charts/secrets-store-sync-controller/values.yaml
Labels: kind/bug, approved, size/S, cncf-cla: yes, lgtm

#62 chore: fixes staging image push
  docker/Makefile
  docker/cloudbuild.yaml
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/XS

#64 ci: updates timeout for staging image build
  docker/Makefile
  docker/cloudbuild.yaml
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/XS

#65 ci: fixes gcloud auth
  docker/Makefile
  docker/cloudbuild.yaml
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/XS

#66 ci: fixes e2e tests workflow
  .github/workflows/e2e-provider-tests.yaml
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/XS

#68 ci: fixes goreleaser
  .goreleaser.yml
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/XS

#67 chore: adds index.html
  charts/index.html
Labels: approved, cncf-cla: yes, lgtm, size/XS, kind/documentation

#73 chore: Update GO_FILES variable in Makefile
  Makefile
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/XS
