Repository kubernetes-sigs/secrets-store-sync-controller, pull requests merged in 2025-03, with the labels that each got.

#95 feat: Adding leader election namespace as param for leader election
  cmd/main.go
Labels: kind/bug, approved, size/S, ok-to-test, cncf-cla: yes, lgtm

#108 security: bump golang.org/x/net to fix CVE-2025-22870
  go.mod
  go.sum
Labels: size/M, approved, cncf-cla: yes, lgtm

#107 ci: add gomod updates to dependabot config
  .github/dependabot.yml
Labels: approved, size/S, cncf-cla: yes, lgtm
